#!/bin/sh

chmod 0755 /usr/libexec/rpcd/vsol_ddm 2>/dev/null || true
[ -x /usr/bin/vsol_query ] && chmod 0755 /usr/bin/vsol_query 2>/dev/null || true
[ -x /usr/libexec/vsol_query ] && chmod 0755 /usr/libexec/vsol_query 2>/dev/null || true

exit 0
