#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG="/usr/libexec/rpcd/vsol_ddm"

start_service() {
	local enabled
	config_load vsol_ddm
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" "daemon"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "vsol_ddm"
}
